### ISSUE TITLE
AN < classid , category name > mapping

### ISSUE THREAD

**Issue by zhengshou** [yjxiong/action-detection#29]
Dear all,

I am working on AN v1.2 now and trying to map the classid used in ssn (which is indexed from 0 to 99) to its original category name. I am wondering does anyone have such mapping file for AN v1.2 and v1.3? Thanks much!

Best,
Zheng

**Comment by yjxiong** [comment]
You can attain the mapping bt sorting the lower-cased class names.

**Comment by zhengshou** [comment]
thanks!

**Comment by mikeleatila** [comment]
Hi @zhengshou , @yjxiong , I am also interested in outputting class label names (e.g. Doing aerobics, Ironing clothes, Brushing teeth, etc.) of detected activities in video instead of 0-99 numbers. Do you know where I can get class label names? Not sure if I understood your comment @yjxiong . Many thanks in advance!

**Comment by yjxiong** [comment]
@mikeleatila  You can attain the mapping bt sorting the lower-cased class names.
